### ISSUE TITLE
V0.3 Feedback

### ISSUE THREAD

**Issue by crphang** [CS2103AUG2016-W14-C1/main#43]
# User Guide
- This explanation doesn't sound right: `deadline : one with just a specific time`. You can express this more clearly.
- As described in class, does it makes sense for the user that Task type cannot be changed? You guys can think about making it more user friendly while dogfooding your application. Is it very intuitive for the user to have to delete a deadline task, and create another event task if he might have decided on the start time afterwards?
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.
- How do you differentiate _View_ with _Search?_ Currently, it is not very clear in your description how _View_ can allow the user to see is different
- You would also like to have some screenshots to explain some of your examples better.

**Comment by 4rr4y** [comment]
Noted and will try to improve UG/program based on the comments. Thanks so much!

**Comment by crphang** [comment]
# Developer Guide Comments
- You can consider have other additions to your Developer's Guide.
1. Adding more description to each components: E.g. showing at least one interactions (Sequence Diagram) within each Component.
2. Explain some unique design pattern that you've implemented. For example, you can describe how your application design handles the Undo functionality.

**Comment by 4rr4y** [comment]
We will look into it soon. Thanks so much for the feedback!
